[package]
name = "pliron"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Programming Languages Intermediate RepresentatiON"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2"
downcast-rs = "1.2.0"
